### PR TITLE
Use uint256 in IStandardToken

### PR DESCRIPTION
**Pull request by quantumagi**
Updates the interface so that amounts are passed as `uint256` values.

See https://github.com/stratisproject/Stratis.SmartContracts/pull/6.

### CODE REVIEW

**Comment by mrtpain** [comment]
Nice! 👏 LGTM, only thoughts are adding a `int GetDecimals()` to this and to match this open PR:  https://github.com/stratisproject/CirrusSmartContracts/pull/17 - used for contracts that might care about how many decimals a token has along with 3rd party apps and wallets that want to display tokens without hard coding or searching for this value elsewhere.

**Comment by YakupIpek** [comment]
It is not need of every token to use such a large numbers. UInt256 has 4x space and has more computational cost so it has a lot higher gas cost than UInt64 . I feel that it may good idea to supports 2 different standard token for UInt256 and UInt64.  

Just a thought

**Comment by YakupIpek** [comment]
Another important point, we introduce to UInt256 mainly avoid overflow cases for multiply balance of 2 different tokens. But we are changing token supply to UInt256 so aren't we gonna hit overflow cases again ? @mrtpain

**Comment by mrtpain** [comment]
@YakupIpek I see your point about it using extra gas and still the same concerns for overflows but my intention and goal behind supporting the change to `UInt256` is really only to match ERC20 standards so wrapping them is possible. 

For example: https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/token/ERC20/ERC20.sol
ERC20 contracts use `UInt256` throughout for all token values. 

Because the max value of `UInt256` is so large, if you get the square root of the max value which equals `340,282,366,920,938,463,463,374,607,431,768,211,455`, this is still larger that most, if not all, existing cryptocurrencies Total Supply. Where an overflow is still possible using `UInt256` for all token values, it is highly unlikely. 

We could have 2 interfaces, one with `UInt64` token values and another with `uint256` token values  but this may cause pain points in many different areas when working with contract integrations and method parameters when calling public methods via FN API. 

I think this approach should only be considered if the average gas cost for a simple `TransferTo` or `TransferFrom` method using `UInt256` is considerably more expensive. Otherwise,  I think we should standardize `uint256` and accept the higher gas costs for all token based values and let developers decide if their contracts should cast from `UInt256`  and persist `UInt64` value types. This will create the standard of using `UInt256` for cross contract calls and public methods when working with token values but allow the developers to have the freedom to store up to the amount they choose.

Thoughts?

**Pull request merged**
